### ISSUE TITLE
Source maps failing to parse in Google Chrome

### ISSUE THREAD

**Issue by danielruiz7** [Urigo/angular-meteor#1898]
Hi, 

I recently upgraded from Meteor 1.6.0.1 to 1.6.1 (thanks for the fix). I also migrated from angular2-compilers to angular-compilers. The app is working  but when I tried to debug the fron-end using Chrome dev tools the source maps are missing. The following is printed in Chrome console:

```
DevTools failed to parse SourceMap: http://localhost:3000/packages/mydaterangepicker.umd.js.map
DevTools failed to parse SourceMap: http://localhost:3000/app/string-util.service.js.map
```

Running the vscode debugger show me more info:

```
SourceMaps.getMapForGeneratedPath: exception while processing path: http://localhost:3000/packages/modules.js?hash=078a0dae0ba337b3a6b6bae13418aa66552f7d7a, sourcemap: mydaterangepicker.umd.js.map
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at new SourceMap (/Users/danielruiz/.vscode/extensions/msjsdiag.debugger-for-chrome-4.2.1/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:20:25)
    at sourceMapContentsP.then.contents (/Users/danielruiz/.vscode/extensions/msjsdiag.debugger-for-chrome-4.2.1/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMapFactory.js:53:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
SourceMaps.getMapForGeneratedPath: exception while processing path: http://localhost:3000/app/app.js?hash=c1de833fc078a7ce55af824967a9654ca9c99b02, sourcemap: string-util.service.js.map
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at new SourceMap (/Users/danielruiz/.vscode/extensions/msjsdiag.debugger-for-chrome-4.2.1/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:20:25)
    at sourceMapContentsP.then.contents (/Users/danielruiz/.vscode/extensions/msjsdiag.debugger-for-chrome-4.2.1/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMapFactory.js:53:28)
    at <anonymous>
```

I also get some compilation errors when starting the app that I didn't get before the upgrade:

```
[client]: ES2015 modules Compilation: 2716.753ms
node_modules/rx/ts/core/linq/observable/pairs.ts (28, 5): Type 'Observable<[string, string]>' is not assignable to type 'Observable<[number, string]>'.
  Type '[string, string]' is not assignable to type '[number, string]'.
    Type 'string' is not assignable to type 'number'.
node_modules/rx/ts/core/linq/observable/pairs.ts (29, 5): Type 'Observable<[string, string]>' is not assignable to type 'Observable<[number, string]>'.
node_modules/rx/ts/core/es5.ts (3, 17): Duplicate identifier 'ObservableOrPromise'.
node_modules/rx/ts/core/es5.ts (5, 17): Duplicate identifier 'ArrayLike'.
node_modules/rx/ts/core/es5.ts (8, 17): Duplicate identifier 'ArrayOrIterable'.
node_modules/rx/ts/core/es6.ts (5, 17): Duplicate identifier 'ObservableOrPromise'.
node_modules/rx/ts/core/es6.ts (7, 17): Duplicate identifier 'ArrayLike'.
node_modules/rx/ts/core/es6.ts (10, 17): Duplicate identifier 'ArrayOrIterable'.
node_modules/rx/ts/core/es6.ts (20, 22): Interface 'IPromise<T>' cannot simultaneously extend types 'PromiseLike<T>' and 'Promise<T>'.
  Named property 'then' of types 'PromiseLike<T>' and 'Promise<T>' are not identical.
node_modules/rx/ts/core/observer-extras.ts (65, 39): Property 'exception' does not exist on type 'Notification<number>'.
[client]: TypeScript Files Compilation: 113.081ms
[client]: HTML Files Compilation: 95.830ms   |
[client]: SCSS Files Compilation: 298.367ms  |
app/client/main.scss: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
[server]: ES2015 modules Compilation: 694.306ms
node_modules/rx/ts/core/linq/observable/pairs.ts (28, 5): Type 'Observable<[string, string]>' is not assignable to type 'Observable<[number, string]>'.
  Type '[string, string]' is not assignable to type '[number, string]'.
    Type 'string' is not assignable to type 'number'.
node_modules/rx/ts/core/linq/observable/pairs.ts (29, 5): Type 'Observable<[string, string]>' is not assignable to type 'Observable<[number, string]>'.
node_modules/rx/ts/core/es5.ts (3, 17): Duplicate identifier 'ObservableOrPromise'.
node_modules/rx/ts/core/es5.ts (5, 17): Duplicate identifier 'ArrayLike'.
node_modules/rx/ts/core/es5.ts (8, 17): Duplicate identifier 'ArrayOrIterable'.
node_modules/rx/ts/core/es6.ts (5, 17): Duplicate identifier 'ObservableOrPromise'.
node_modules/rx/ts/core/es6.ts (7, 17): Duplicate identifier 'ArrayLike'.
node_modules/rx/ts/core/es6.ts (10, 17): Duplicate identifier 'ArrayOrIterable'.
node_modules/rx/ts/core/es6.ts (20, 22): Interface 'IPromise<T>' cannot simultaneously extend types 'PromiseLike<T>' and 'Promise<T>'.
  Named property 'then' of types 'PromiseLike<T>' and 'Promise<T>' are not identical.
node_modules/rx/ts/core/observer-extras.ts (65, 39): Property 'exception' does not exist on type 'Notification<number>'.
server/admin/admin-reservations.publication.ts (368, 36): Property 'aggregate' does not exist on type 'Collection<Reservation>'.
server/admin/clients.publication.ts (54, 3): Type 'Mongo.Cursor<Client>' is not assignable to type 'Mongo.Cursor<Client>'. Two different types with this name exist, but they are unrelated.
  Types of property 'forEach' are incompatible.
    Type '(callback: <T>(doc: T, index: number, cursor: Cursor<T>) => void, thisArg?: any) => void' is not assignable to type '(callback: (doc: Client, index: number, cursor: Cursor<Client>) => void, thisArg?: any) => void'.
      Types of parameters 'callback' and 'callback' are incompatible.
        Types of parameters 'doc' and 'doc' are incompatible.
          Type 'T' is not assignable to type 'Client'.
server/admin/clients.publication.ts (67, 3): Type 'Mongo.Cursor<Reservation>' is not assignable to type 'Mongo.Cursor<Reservation>'. Two different types with this name exist, but they are unrelated.
  Types of property 'forEach' are incompatible.
    Type '(callback: <T>(doc: T, index: number, cursor: Cursor<T>) => void, thisArg?: any) => void' is not assignable to type '(callback: (doc: Reservation, index: number, cursor: Cursor<Reservation>) => void, thisArg?: any)...'.
      Types of parameters 'callback' and 'callback' are incompatible.
        Types of parameters 'doc' and 'doc' are incompatible.
          Type 'T' is not assignable to type 'Reservation'.
server/admin/shop-resources.methods.ts (181, 43): Property '_id' does not exist on type 'T'.
server/admin/shop-resources.methods.ts (182, 34): Property '_id' does not exist on type 'T'.
server/admin/shop-resources.methods.ts (184, 34): Property '_id' does not exist on type 'T'.
server/admin/shop-resources.publitcation.ts (19, 3): Type 'Mongo.Cursor<ShopResource>' is not assignable to type 'Mongo.Cursor<ShopResource>'. Two different types with this name exist, but they are unrelated.
  Types of property 'forEach' are incompatible.
    Type '(callback: <T>(doc: T, index: number, cursor: Cursor<T>) => void, thisArg?: any) => void' is not assignable to type '(callback: (doc: ShopResource, index: number, cursor: Cursor<ShopResource>) => void, thisArg?: an...'.
      Types of parameters 'callback' and 'callback' are incompatible.
        Types of parameters 'doc' and 'doc' are incompatible.
          Type 'T' is not assignable to type 'ShopResource'.
server/admin/shop-services.publitcation.ts (18, 3): Type 'Mongo.Cursor<ShopService>' is not assignable to type 'Mongo.Cursor<ShopService>'. Two different types with this name exist, but they are unrelated.
  Types of property 'forEach' are incompatible.
    Type '(callback: <T>(doc: T, index: number, cursor: Cursor<T>) => void, thisArg?: any) => void' is not assignable to type '(callback: (doc: ShopService, index: number, cursor: Cursor<ShopService>) => void, thisArg?: any)...'.
      Types of parameters 'callback' and 'callback' are incompatible.
        Types of parameters 'doc' and 'doc' are incompatible.
          Type 'T' is not assignable to type 'ShopService'.
server/admin/stats.methods.ts (43, 36): Property 'aggregate' does not exist on type 'Collection<Reservation>'.
server/admin/stats.methods.ts (84, 36): Property 'aggregate' does not exist on type 'Collection<Reservation>'.
server/admin/stats.methods.ts (125, 36): Property 'aggregate' does not exist on type 'Collection<Reservation>'.
server/admin/stats.methods.ts (168, 36): Property 'aggregate' does not exist on type 'Collection<Reservation>'.
server/publications/reservations.publication.ts (29, 3): Type 'Mongo.Cursor<Reservation>' is not assignable to type 'Mongo.Cursor<Reservation>'. Two different types with this name exist, but they are unrelated.
  Types of property 'forEach' are incompatible.
    Type '(callback: <T>(doc: T, index: number, cursor: Cursor<T>) => void, thisArg?: any) => void' is not assignable to type '(callback: (doc: Reservation, index: number, cursor: Cursor<Reservation>) => void, thisArg?: any)...'.
      Types of parameters 'callback' and 'callback' are incompatible.
        Types of parameters 'doc' and 'doc' are incompatible.
          Type 'T' is not assignable to type 'Reservation'.
server/reCAPTCHA.ts (32, 96): Argument of type '{ content: any; headers: { 'Content-Type': string; 'Content-Length': number; }; }' is not assignable to parameter of type 'HTTPRequest'.
  Types of property 'headers' are incompatible.
    Type '{ 'Content-Type': string; 'Content-Length': number; }' is not assignable to type '{ [id: string]: string; }'.
      Property ''Content-Length'' is incompatible with index signature.
        Type 'number' is not assignable to type 'string'.
[server]: TypeScript Files Compilation: 76.805ms
[server]: HTML Files Compilation: 0.091ms    |
[server]: SCSS Files Compilation: 0.086ms    |
```

Meteor versions file:

```
accounts-base@1.4.2
accounts-facebook@1.3.1
accounts-google@1.3.1
accounts-oauth@1.1.15
accounts-password@1.5.1
alanning:roles@1.2.16
allow-deny@1.1.0
angular-compilers@0.2.9_3
angular-html-compiler@0.2.9
angular-scss-compiler@0.2.9_1
angular-typescript-compiler@0.2.9_7
autoupdate@1.4.0
babel-compiler@7.0.5
babel-runtime@1.2.2
base64@1.0.11
binary-heap@1.0.10
blaze@2.3.2
blaze-tools@1.0.10
boilerplate-generator@1.4.0
caching-compiler@1.1.11
caching-html-compiler@1.1.2
callback-hook@1.1.0
check@1.3.1
ddp@1.4.0
ddp-client@2.3.2
ddp-common@1.4.0
ddp-rate-limiter@1.0.7
ddp-server@2.1.2
deps@1.0.12
diff-sequence@1.1.0
dynamic-import@0.3.0
ecmascript@0.10.5
ecmascript-runtime@0.5.0
ecmascript-runtime-client@0.6.2
ecmascript-runtime-server@0.5.0
ejson@1.1.0
email@1.2.3
es5-shim@4.7.3
facebook-oauth@1.4.0
geojson-utils@1.0.10
google-oauth@1.2.5
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.4.0
id-map@1.1.0
jalik:ufs@0.7.4_1
jalik:ufs-gridfs@0.2.1
jquery@1.11.11
launch-screen@1.1.1
livedata@1.0.18
localstorage@1.2.0
logging@1.1.20
matb33:collection-hooks@0.8.4
meteor@1.8.6
meteor-base@1.3.0
meteorhacks:aggregate@1.3.0
meteorhacks:collection-utils@1.2.0
minifier-css@1.3.1
minifier-js@2.3.3
minimongo@1.4.3
mobile-experience@1.0.5
mobile-status-bar@1.0.14
modules@0.11.5
modules-runtime@0.9.2
mongo@1.4.5
mongo-dev-server@1.1.0
mongo-id@1.0.7
mongo-livedata@1.0.12
npm-bcrypt@0.9.3
npm-mongo@2.2.34
oauth@1.2.1
oauth2@1.2.0
observe-sequence@1.0.16
ordered-dict@1.1.0
promise@0.10.2
random@1.1.0
rate-limit@1.0.9
reactive-var@1.0.11
reload@1.2.0
retry@1.1.0
reywood:publish-composite@1.5.2
routepolicy@1.0.13
server-render@0.3.0
service-configuration@1.0.11
sha@1.0.9
shell-server@0.3.1
shim-common@0.1.0
socket-stream-client@0.1.0
spacebars@1.0.15
spacebars-compiler@1.1.3
srp@1.0.10
standard-minifier-css@1.4.1
standard-minifier-js@2.3.2
templating@1.3.2
templating-compiler@1.3.3
templating-runtime@1.3.2
templating-tools@1.1.2
tmeasday:check-npm-versions@0.3.2
tracker@1.1.3
underscore@1.0.10
url@1.2.0
webapp@1.5.0
webapp-hashing@1.0.9
```

package.json

```
{
  "name": "shop",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "@angular/animations": "^5.2.9",
    "@angular/common": "^5.2.9",
    "@angular/compiler": "^5.2.9",
    "@angular/core": "^5.2.9",
    "@angular/forms": "^5.2.9",
    "@angular/http": "^5.2.9",
    "@angular/platform-browser": "^5.2.9",
    "@angular/platform-browser-dynamic": "^5.2.9",
    "@angular/platform-server": "^5.2.9",
    "@angular/router": "^5.2.9",
    "@babel/runtime": "^7.0.0-beta.42",
    "@ng-select/ng-select": "^0.17.2",
    "@types/googlemaps": "^3.30.8",
    "angular2-meteor-polyfills": "^0.2.0",
    "ap-angular2-fullcalendar": "^1.3.7",
    "babel-runtime": "^6.26.0",
    "bcrypt": "^1.0.3",
    "bootstrap": "^4.0.0",
    "chart.js": "^2.7.2",
    "fullcalendar": "^3.9.0",
    "gm": "^1.23.1",
    "meteor-node-stubs": "~0.2.4",
    "meteor-rxjs": "^0.4.10",
    "moment": "^2.21.0",
    "mydatepicker": "^2.6.3",
    "mydaterangepicker": "^4.2.1",
    "ng2-currency-mask": "^4.4.1",
    "ng2-dnd": "^5.0.2",
    "ngx-infinite-scroll": "^0.8.3",
    "ngx-papaparse": "^1.2.5",
    "node-schedule": "^1.3.0",
    "reflect-metadata": "^0.1.12",
    "rxjs": "^5.5.0",
    "spawn-sync": "^1.0.15",
    "try-thread-sleep": "^1.0.2",
    "typings": "^2.1.1",
    "underscore": "^1.8.3",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^5.2.9",
    "@types/chartjs": "0.0.31",
    "@types/meteor": "^1.4.13",
    "@types/meteor-publish-composite": "0.0.32",
    "@types/meteor-roles": "^1.2.29",
    "@types/node": "^9.4.7",
    "@types/underscore": "^1.8.8",
    "typescript": "^2.6.2"
  }
}

```

tsconfig.json

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "importHelpers": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es2015",
    "skipLibCheck": true,
    "stripInternal": true,
    "noImplicitAny": false,
    "types": [
      "typings.d",
      "@types/node",
      "@types/meteor",
      "@types/meteor-roles",
      "@types/googlemaps",
      "@types/meteor-publish-composite"
    ]
  },
  "include": [
    "client/**/*.ts",
    "server/**/*.ts",
    "imports/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "files": [
    "typings.d.ts"
  ],
  "compileOnSave": false,
  "angularCompilerOptions": {
    "genDir": "aot",
    "skipMetadataEmit": true
  }
}
```

Is something wrong?

**Comment by ardatan** [comment]
Could you run
`npm update` and `meteor update --all-packages --allow-incompatible-update` ?

**Comment by danielruiz7** [comment]
Now the app is crashing :-(

[trace.txt](https://github.com/Urigo/angular-meteor/files/1836826/trace.txt)

**Comment by bouchepat** [comment]
I have the same issue with the source maps failing to parse (Google Chrome) which makes debugging impossible. I reverted to previous version for development and kept updated version ( 1.6.1) for production.

**Comment by ardatan** [comment]
@danielruiz7 The latest error you get is due to a different error, if you update again, this error will be gone.
And please write here the errors after you update by the commands I send.

**Comment by ardatan** [comment]
I think it tries to compile 'rx' not 'rxjs'. You need to reinstall your node_modules to delete them.
```
rm -rf node_modules
npm install
```
For css errors, the imports have to be in the beginning of the file.
Finally, the other errors is about your source files.

**Comment by ardatan** [comment]
Please let us know if the problem is fixed or still occurres.

**Comment by danielruiz7** [comment]
I managed to fix the compilation errors (except for the fact that rx package is automatically added and I have to remove it every time I run npm install...), but source maps are still failing to parse in Google Chrome. Are you able to replicate the problem? I could create a repo if you like

**Comment by ardatan** [comment]
Thanks, It would be great if you reproduce a repo

**Comment by danielruiz7** [comment]
Here it is:

https://github.com/danielruiz7/src-maps-chrome

**Comment by pedrolucasoliva** [comment]
My crew and I meet same problem here.

**Comment by pedrolucasoliva** [comment]
I downgraded the meteor and came back to work:
`meteor update --release 1.6`

**Comment by kodibear** [comment]
I'm also facing the same problem after upgrading from 1.6.0 to 1.6.1. I followed the migration guide in the patch notes and all of the packages are at the latest version. The only source files that are available for me in Chrome DevTools are .coffeescript files (no .js ones) and it's impossible to debug client code anymore.

**Comment by amersabag** [comment]
This is also happening to me. I downgraded to Meteor 1.6.0.1.

**Comment by bouchepat** [comment]
Is there any update on this issue?

**Comment by araad** [comment]
It seems this issue is not related to this package. I tried creating a new project with 1.6.1.1 without the angular compilers and instead used barbatus:typescript and in chrome I get the "failed to parse SourceMap" warning but it works fine on Firefox.
