### ISSUE TITLE
Windows 10 can't run angular2-compilers with meteor 1.6. Node-sass http 404

### ISSUE THREAD

**Issue by pedrofg** [Urigo/angular-meteor#1850]
![image](https://user-images.githubusercontent.com/8161635/34494048-9263c072-efbc-11e7-8885-274216819622.png)

Working on Windows 10.
Meteor version 1.6.0.1
Meteor node version 8.9.3

Getting this error after updating the meteor version from 1.5 to 1.6 in the project. 
Looks like this package angular2-compilers@0.6.6 tries to download this node-sass version which is not in the repository.

Have anyone had this issue?

**Comment by ardatan** [comment]
Please use angular-compilers which is the new name of the package.

**Comment by pedrofg** [comment]
If i remove angular2-compilers and add the angular-compilers i have a lot of different errors, i believe that to change it, it is not simply just remove one and add another.

This error does not happen on Linux.

**Comment by ardatan** [comment]
Could you share new errors, so we can help you better?

**Comment by ab-ankhbayar** [comment]
When I removed angular2-compilers and add angular-compilers, compiling shows  ton of errors. And I found this it's related to declarations.d.ts file. In declarations.d.ts file, there are declarations of global variables. Errors shows that cannot find name 'the variable name declared in declarations.d.ts'. Any help?
