### ISSUE TITLE
No meteor.d.ts file in typings folder

### ISSUE THREAD

**Issue by Hongbo-Miao** [Urigo/angular-meteor#1163]
Before there is a **typings/meteor/meteor.d.ts** file.

After updating from 0.3.7 to 0.4.0. The program does not download **meteor.d.ts** by itself.

So when run the app, it shows:

> Cannot find name 'Meteor'.

**EDIT: es6-promise.d.ts and es6-shim.d.ts are also not downloaded.**

**Comment by Tallyb** [comment]
+1

**Comment by Splaktar** [comment]
I saw this as well and opened https://github.com/Urigo/meteor-angular2.0-socially/issues/41 to track it and provide some workarounds.

**Comment by barbatus** [comment]
Yes, most typings are available on [DefinitelyTyped](http://definitelytyped.org/), so the right way will be to install them from there. From other side, typings created specially for packages or declaration files that are distributed via NPM packages (like in case of Angular 2) will be still installed by Angular2-Meteor and related packages.

In order to install Meteor typings, you will need to run:

````
npm install tsd -g
tsd install meteor
```

The tutorial has been updated accordingly.

**Comment by Urigo** [comment]
deployed the new changes

**Comment by Tallyb** [comment]
@barbatus  tsd is marked as deprecated, and typings should be installed.

**Comment by Hongbo-Miao** [comment]
thanks!

**Comment by barbatus** [comment]
@tally right, I am fixing it already. thx for pointing that out.
