### ISSUE TITLE
Whatsapp clone tutorial with Meteor 1.3

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular-meteor#1209]
Bring everything from Npm

**Comment by jboothe** [comment]
Uri, will 1.3.6 work with Meteor 1.3?

**Comment by Urigo** [comment]
`angular@1.3.7` works with both Meteor 1.3 and Meteor 1.2

**Comment by jmwierzbicki** [comment]
I had updated my meteor to "meteor update --release METEOR@1.3-modules-beta.8", but after that, when i run meteor, my site crashes, and it is said that it cant find module 'angular'

Uncaught Error: Cannot find module 'angular'require @ install.js:77(anonymous function) @ templates-handler.js:3(anonymous function) @ angular-templates.js?hash=c260fbc3137ab92e420262912f9b307ce8e4de7a:60(anonymous function) @ angular-templates.js?hash=c260fbc3137ab92e420262912f9b307ce8e4de7a:67
sockjs-0.3.4.js:854 GET http://localhost/sockjs/info?cb=761y08sd3s net::ERR_CONNECTION_REFUSEDAbstractXHRObject._start @ sockjs-0.3.4.js:854(anonymous function) @ sockjs-0.3.4.js:888

**Comment by kamilkisiela** [comment]
@jmwierzbicki are you sure that you're using `1.3.7`?

**Comment by jmwierzbicki** [comment]
hey, i installed meteor on virtual machine, as i heard that there is much better building times, also new meteor 1.3 rc2 does not support windows. anyway my application builds sucessfully, server does not spew any error. Unfortunatelly angular crashes in browser.

this is error copied from browser console:

`
modules-runtime.js?hash=e89b5fd26ee523597cd366bf9f71585253b20e5d:105 Uncaught Error: Cannot find module 'angular'require @ modules-runtime.js?hash=e89b5fd26ee523597cd366bf9f71585253b20e5d:105(anonymous function) @ angular-templates.js?hash=5022e4aabeeb8968588154bd4a613a92795bed42:28(anonymous function) @ angular-templates.js?hash=5022e4aabeeb8968588154bd4a613a92795bed42:60(anonymous function) @ angular-templates.js?hash=5022e4aabeeb8968588154bd4a613a92795bed42:67
angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:93 Uncaught Error: [$injector:nomod] Module 'angular-templates' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=angular-templates(anonymous function) @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:93(anonymous function) @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:2030ensure @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:1954module @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:2028(anonymous function) @ template.aspect-list-editor-import.js?hash=f795776142a9f3afd025c2cf0b6c70dc4f412a50:1(anonymous function) @ template.aspect-list-editor-import.js?hash=f795776142a9f3afd025c2cf0b6c70dc4f412a50:2
angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:93 Uncaught Error: [$injector:nomod] Module 'angular-templates' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=angular-templates(anonymous function) @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:93(anonymous function) @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:2030ensure @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:1954module @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:2028(anonymous function) @ template.aspect-uploader-directive.js?hash=feac0623dd79ad45adfc6226d86023c9a52841a2:1(anonymous function) @ template.aspect-uploader-directive.js?hash=feac0623dd79ad45adfc6226d86023c9a52841a2:2
angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:93 Uncaught Error: [$injector:nomod] Module 'angular-templates' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=angular-templates(anonymous function) @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:93(anonymous function) @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:2030ensure @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:1954module @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:2028(anonymous function) @ template.aspect-uploader-directive2.js?hash=595ac95e0d9b965de42c57bb3d92bc2e864ab772:1(anonymous function) @ template.aspect-uploader-directive2.js?hash=595ac95e0d9b965de42c57bb3d92bc2e864ab772:2
angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:93 Uncaught Error: [$injector:nomod] Module 'angular-templates' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=angular-templates(anonymous function) @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:93(anonymous function) @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:2030ensure @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:1954module @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:2028(anonymous function) @ template.aspect-list-editor.js?hash=c20f7a8004b38c96ea71f66edbd277f29587238d:1(anonymous function) @ template.aspect-list-editor.js?hash=c20f7a8004b38c96ea71f66edbd277f29587238d:2
angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:93 Uncaught Error: [$injector:nomod] Module 'angular-templates' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=angular-templates(anonymous function) @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:93(anonymous function) @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:2030ensure @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:1954module @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:2028(anonymous function) @ template.bundle-list.js?hash=2cc35a5f9777df3951ee1cd64e2eb888f79090e0:1(anonymous function) @ template.bundle-list.js?hash=2cc35a5f9777df3951ee1cd64e2eb888f79090e0:2
angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:93 Uncaught Error: [$injector:nomod] Module 'angular-templates' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=angular-templates(anonymous function) @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:93(anonymous function) @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:2030ensure @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:1954module @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:2028(anonymous function) @ template.solver.js?hash=d8fee0a919ac59610eb57572dac73afcb243c41b:1(anonymous function) @ template.solver.js?hash=d8fee0a919ac59610eb57572dac73afcb243c41b:2
angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:93 Uncaught Error: [$injector:nomod] Module 'angular-templates' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=angular-templates(anonymous function) @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:93(anonymous function) @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:2030ensure @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:1954module @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:2028(anonymous function) @ template.test.js?hash=2595f5a298781f0a6c32899345ad26f89bbea29b:1(anonymous function) @ template.test.js?hash=2595f5a298781f0a6c32899345ad26f89bbea29b:2
angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:93 Uncaught Error: [$injector:nomod] Module 'angular-templates' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=angular-templates(anonymous function) @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:93(anonymous function) @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:2030ensure @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:1954module @ angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:2028(anonymous function) @ template.test2.js?hash=9601e9c6fe6820d3ec4e50fb3c40d77fe71f1aef:1(anonymous function) @ template.test2.js?hash=9601e9c6fe6820d3ec4e50fb3c40d77fe71f1aef:2
app.js:51 app initialized
angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:93 Uncaught Error: [$injector:modulerr] Failed to instantiate module socially due to:
Error: [$injector:modulerr] Failed to instantiate module angular-meteor due to:
Error: [$injector:nomod] Module 'angular-meteor' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=angular-meteor
    at http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:93:12
    at http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:2030:17
    at ensure (http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:1954:38)
    at module (http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:2028:14)
    at http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:4460:22
    at forEach (http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:365:20)
    at loadModules (http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:4444:5)
    at http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:4461:40
    at forEach (http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:365:20)
    at loadModules (http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:4444:5)
http://errors.angularjs.org/1.4.8/$injector/modulerr?p0=angular-meteor&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'angular-meteor'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.8%2F%24injector%2Fnomod%3Fp0%3Dangular-meteor%0A%20%20%20%20at%20http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A93%3A12%0A%20%20%20%20at%20http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A2030%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A1954%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A2028%3A14)%0A%20%20%20%20at%20http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A4460%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A365%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A4444%3A5)%0A%20%20%20%20at%20http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A4461%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A365%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A4444%3A5)
    at http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:93:12
    at http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:4483:15
    at forEach (http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:365:20)
    at loadModules (http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:4444:5)
    at http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:4461:40
    at forEach (http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:365:20)
    at loadModules (http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:4444:5)
    at createInjector (http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:4369:11)
    at doBootstrap (http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:1701:20)
    at Object.bootstrap (http://192.168.1.109/packages/angular_angular.js?hash=744f2a24d25bc044c522c2b73d99ed3f9da1cfd1:1722:12)
http://errors.angularjs.org/1.4.8/$injector/modulerr?p0=socially&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20angular-meteor%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'angular-meteor'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.8%2F%24injector%2Fnomod%3Fp0%3Dangular-meteor%0A%20%20%20%20at%20http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A93%3A12%0A%20%20%20%20at%20http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A2030%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A1954%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A2028%3A14)%0A%20%20%20%20at%20http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A4460%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A365%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A4444%3A5)%0A%20%20%20%20at%20http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A4461%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A365%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A4444%3A5)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.8%2F%24injector%2Fmodulerr%3Fp0%3Dangular-meteor%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'angular-meteor'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.4.8%252F%2524injector%252Fnomod%253Fp0%253Dangular-meteor%250A%2520%2520%2520%2520at%2520http%253A%252F%252F192.168.1.109%252Fpackages%252Fangular_angular.js%253Fhash%253D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%253A93%253A12%250A%2520%2520%2520%2520at%2520http%253A%252F%252F192.168.1.109%252Fpackages%252Fangular_angular.js%253Fhash%253D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%253A2030%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(http%253A%252F%252F192.168.1.109%252Fpackages%252Fangular_angular.js%253Fhash%253D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%253A1954%253A38)%250A%2520%2520%2520%2520at%2520module%2520(http%253A%252F%252F192.168.1.109%252Fpackages%252Fangular_angular.js%253Fhash%253D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%253A2028%253A14)%250A%2520%2520%2520%2520at%2520http%253A%252F%252F192.168.1.109%252Fpackages%252Fangular_angular.js%253Fhash%253D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%253A4460%253A22%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252F192.168.1.109%252Fpackages%252Fangular_angular.js%253Fhash%253D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%253A365%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252F192.168.1.109%252Fpackages%252Fangular_angular.js%253Fhash%253D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%253A4444%253A5)%250A%2520%2520%2520%2520at%2520http%253A%252F%252F192.168.1.109%252Fpackages%252Fangular_angular.js%253Fhash%253D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%253A4461%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252F192.168.1.109%252Fpackages%252Fangular_angular.js%253Fhash%253D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%253A365%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252F192.168.1.109%252Fpackages%252Fangular_angular.js%253Fhash%253D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%253A4444%253A5)%0A%20%20%20%20at%20http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A93%3A12%0A%20%20%20%20at%20http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A4483%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A365%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A4444%3A5)%0A%20%20%20%20at%20http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A4461%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A365%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A4444%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A4369%3A11)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A1701%3A20)%0A%20%20%20%20at%20Object.bootstrap%20(http%3A%2F%2F192.168.1.109%2Fpackages%2Fangular_angular.js%3Fhash%3D744f2a24d25bc044c522c2b73d99ed3f9da1cfd1%3A1722%3A12)
`

 this is my meteor list output 

`
accounts-facebook                  1.0.7-rc.2  Login service for Facebook accounts
accounts-password                  1.1.6-rc.2  Password support for accounts
accounts-twitter                   1.0.7-rc.2  Login service for Twitter accounts
accounts-ui                        1.1.7-rc.2  Simple templates to add login widgets to an app
accounts-ui-unstyled               1.1.10-rc.2  Unstyled version of login widgets
angular                            1.3.7  Everything you need to use AngularJS in your Meteor app
angular:angular-material           1.0.6  Google Material design written for AngularJs (official repo)
angularui:angular-ui-router        0.2.15  angular-ui-router (official): Flexible routing with nested views in AngularJS
angularutils:pagination            0.9.1_2  Magical automatic pagination for anything in AngularJS
brettle:accounts-anonymous         0.3.1  Support anonymous logins
brettle:accounts-anonymous-auto    0.3.5  Automatically create anonymous accounts for each new visitor
brettle:accounts-deluxe            0.2.1* Give all visitors anonymous accounts to which a login service can be added with popular UI packages
brettle:accounts-logout-to-switch  0.4.2  Requires that signed up users sign out before they sign in to another existing account.
brettle:accounts-patch-ui          0.1.3* Monkey patches accounts UI packages to support logged in users who have not signed up.
cfs:filesystem                     0.1.2  Filesystem storage adapter for CollectionFS
cfs:s3                             0.1.3  Amazon Web Services S3 storage adapter for CollectionFS
cfs:standard-packages              0.5.9  Filesystem for Meteor, collectionFS
cfs:ui                             0.1.3  CollectionFS, provides UI helpers
dotansimha:accounts-ui-angular     0.0.2  AngularJS wrapper for Meteor's Account-UI package
es5-shim                           4.5.8-rc.2  Shims and polyfills to improve ECMAScript 5 support
jagi:astronomy                     1.2.10  Model layer for Meteor
jquery                             1.11.6-rc.2  Manipulate the DOM using CSS selectors
matb33:collection-hooks            0.8.1  Extends Mongo.Collection with before/after hooks for insert/update/remove/find/findOne
meteor-base                        1.0.2-rc.2  Packages that every Meteor app needs
meteorhacks:fast-render            2.13.0  Render your app before the DDP connection even comes alive - magic?
meteorhacks:kadira                 2.28.5  Performance Monitoring for Meteor
mobile-experience                  1.0.2-rc.2  Packages for a great mobile user experience
mongo                              1.1.5-rc.2  Adaptor for using MongoDB and Minimongo over DDP
msavin:mongol                      1.6.2  In-App MongoDB Editor
session                            1.1.3-rc.2  Session variable
standard-minifier-css              1.0.4-rc.2  Standard css minifier used with Meteor apps by default.
standard-minifier-js               1.0.4-rc.2  Standard javascript minifiers used with Meteor apps by default.
tmeasday:publish-counts            0.7.3  Publish the count of a cursor, in real time
tracker                            1.0.11-rc.2  Dependency tracker to allow reactive callbacks
u2622:persistent-session           0.4.4  Persistently store Session data on the client
`

**Comment by kamilkisiela** [comment]
@jmwierzbicki I'm going to check it

**Comment by jmwierzbicki** [comment]
Quick way to reproduce my issue: 

meteor create testapp
unpack step 3 tutorial to testapp
meteor update
meteor update --release METEOR@1.3-rc.2 

it should be broken at this point.

tested on debian 8 x32

**Comment by fpaboim** [comment]
Having the same problem updating here:

Uncaught Error: Cannot find module 'angular'require @ modules-runtime.js:105

**Comment by jmwierzbicki** [comment]
#1277

**Comment by Urigo** [comment]
the new Whatsapp tutorials now work with Meteor 1.3
