### ISSUE TITLE
1.3.6 : $rootScope can not be reactive as other scopes

### ISSUE THREAD

**Issue by michaelszt** [Urigo/angular-meteor#1238]
Description on first comment

**Comment by michaelszt** [comment]
After I update my project to 1.3.6, I get this error : 

TypeError: scope.viewModel is not a function
    at Reactive.attach (angular-meteor-data.js:1798)
    at new controller (card-tools.component.js:11)
    at Object.invoke (angular_angular.js:4546)
    at extend.instance (angular_angular.js:9205)
    at nodeLinkFn (angular_angular.js:8322)
    at angular_angular.js:8595
    at processQueue (angular_angular.js:14815)
    at angular_angular.js:14831
    at Scope.$eval (angular_angular.js:16075)
    at Scope.$digest (angular_angular.js:15893)

here is my code:

(function(){
    'use strict';

  angular.module('Aries').directive('cardtools', function () {
    return {
      restrict: 'E',
      templateUrl: 'client/card-tools/card-tools.html',
      controllerAs: 'cardtools',
      controller: function ($scope, $reactive, $mdSidenav, $state, ssSideNav, ssSideNavSharedService) {
        $reactive(this).attach($scope);
          /* jshint validthis: true */
          var vm = this;


      }
    }
  });

})();

**Comment by ozsay** [comment]
Can you share your meteor versions file ?

**Comment by michaelszt** [comment]
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
session                 # Client-side reactive dictionary for your app
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifiers      # JS/CSS minifiers run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.

angular
angularui:angular-ui-router
accounts-password
dotansimha:accounts-ui-angular
angularutils:pagination
tmeasday:publish-counts
check
email
less
angularui:angular-ui-bootstrap
angular:angular-material
planettraining:material-design-icons
alanning:roles

#for test
msavin:mongol

**Comment by ozsay** [comment]
@michaelszt this the the packages file, in the same folder there is the versions file. Can you share it as well?

Thanks

**Comment by michaelszt** [comment]
accounts-base@1.2.2
accounts-password@1.1.4
accounts-ui@1.1.6
accounts-ui-unstyled@1.1.8
alanning:roles@1.2.14
angular@1.3.6
angular-meteor-data@0.2.0
angular-templates@0.0.3
angular:angular@1.5.0
angular:angular-animate@1.5.0
angular:angular-aria@1.5.0
angular:angular-material@1.0.5
angularui:angular-ui-bootstrap@0.13.0
angularui:angular-ui-router@0.2.15
angularutils:pagination@0.9.1_2
autoupdate@1.2.4
babel-compiler@5.8.24_1
babel-runtime@0.1.4
base64@1.0.4
benjamine:jsondiffpatch@0.1.38_1
binary-heap@1.0.4
blaze@2.1.3
blaze-html-templates@1.0.1
blaze-tools@1.0.4
boilerplate-generator@1.0.4
caching-compiler@1.0.0
caching-html-compiler@1.0.2
callback-hook@1.0.4
check@1.1.0
dburles:mongo-collection-instances@0.3.4
ddp@1.2.2
ddp-client@1.2.1
ddp-common@1.2.2
ddp-rate-limiter@1.0.0
ddp-server@1.2.2
deps@1.0.9
diff-sequence@1.0.1
dotansimha:accounts-ui-angular@0.0.2
ecmascript@0.1.6
ecmascript-runtime@0.2.6
ejson@1.0.7
email@1.0.8
es5-shim@4.1.14
fastclick@1.0.7
geojson-utils@1.0.4
hot-code-push@1.0.0
html-tools@1.0.5
htmljs@1.0.5
http@1.1.1
id-map@1.0.4
jquery@1.11.4
lai:collection-extensions@0.1.4
launch-screen@1.0.4
less@2.5.1
livedata@1.0.15
localstorage@1.0.5
logging@1.0.8
meteor@1.1.10
meteor-base@1.0.1
meteortoys:toykit@2.2.1
minifiers@1.1.7
minimongo@1.0.10
mobile-experience@1.0.1
mobile-status-bar@1.0.6
mongo@1.1.3
mongo-id@1.0.1
msavin:mongol@1.6.2
npm-bcrypt@0.7.8_2
npm-mongo@1.4.39_1
observe-sequence@1.0.7
ordered-dict@1.0.4
pbastowski:angular-babel@1.0.9
planettraining:material-design-icons@2.1.1
promise@0.5.1
random@1.0.5
rate-limit@1.0.0
reactive-dict@1.1.3
reactive-var@1.0.6
reload@1.1.4
retry@1.0.4
routepolicy@1.0.6
service-configuration@1.0.5
session@1.1.1
sha@1.0.4
spacebars@1.0.7
spacebars-compiler@1.0.7
srp@1.0.4
standard-minifiers@1.0.2
templating@1.1.5
templating-tools@1.0.0
tmeasday:publish-counts@0.7.3
tracker@1.0.9
ui@1.0.8
underscore@1.0.4
url@1.0.5
webapp@1.2.3
webapp-hashing@1.0.5

**Comment by ozsay** [comment]
I don't see any issue with the versions. Can you share a repository so I can reproduce the error?

**Comment by cleor41** [comment]
I received the same issue today

**Comment by nunof07** [comment]
I have the same issue.

Seems to only happen for directives placed directly in the body. Everything inside `ui-view` seems to work fine.

My HTML file is in the root folder.

This was also mentioned here: https://github.com/Urigo/angular-meteor/issues/1110#issuecomment-184462418

**Comment by ozsay** [comment]
@cleor41 @nunof07 Can you share a repository so we'll investigate the issue ? Thanks

**Comment by ozsay** [comment]
I think I just encountered this issue.

It looks like it will happen on the `$rootScope`.

@cleor41 @nunof07 Can you see if the scope that creates this issue is the root ?

**Comment by cubitworx** [comment]
@ozsay Yes, it appears to be related to the root scope. As soon as I comment out `$reactive(this).attach($scope);` in the controller where $scope is the $rootScope the error goes away.

**Comment by cleor41** [comment]
After I commented out the "reactive scope attach" line I received another error on "this.helpers". I can send a repo over as soon as I get home.

**Comment by nunof07** [comment]
Here is a very basic setup to reproduce this issue: https://github.com/nunof07/angular-meteor-issue1238

Root file:

```
<body ng-app="myapp" ng-strict-di="">
    <hello-world></hello-world>
</body>
```

Directive:

```
angular.module('myapp').directive('helloWorld', function () {
    return {
        restrict: 'E',
        templateUrl: 'client/hello-world/hello-world.html',
        controllerAs: 'helloWorld',
        controller: function ($scope, $reactive) {
            $reactive(this).attach($scope);
        }
    };
});
```

Error message:

```
TypeError: scope.viewModel is not a function
    at Reactive.attach (view-model.js:79)
    at new controller (hello-world.component.js:7)
    at Object.invoke (angular.js:4523)
    at extend.instance (angular.js:9182)
    at nodeLinkFn (angular.js:8299)
    at angular.js:8572
    at processQueue (angular.js:14792)
    at angular.js:14808
    at Scope.$eval (angular.js:16052)
    at Scope.$digest (angular.js:15870)(anonymous function) @ angular.js:12520
```

**Comment by cleor41** [comment]
I made a branch to show the error. Clone it down and run meteor to see the error.

**Comment by michaelszt** [comment]
Now I update angular:angular to 1.5.0, I found if I change directive to component then it works good. Here is my new code:
`
(function(){
    'use strict';

  angular.module('Aries').component('cardtools', {
      templateUrl: 'client/card-tools/card-tools.html',
      controller: cardtoolsCtrl
    
  });

  cardtoolsCtrl.$inject = ['$scope', '$reactive','$mdSidenav', '$state', 'ssSideNav', 'ssSideNavSharedService'];


  function cardtoolsCtrl($scope, $reactive, $mdSidenav, $state, ssSideNav, ssSideNavSharedService) {
        $reactive(this).attach($scope);
          /* jshint validthis: true */
          var vm = this;

          vm.toggleSidenav = toggleSidenav;

          $scope.menu = ssSideNav;

          
          vm.autorun(() => {
            //Meteor.user()会延迟加载
            if (Roles.userIsInRole(Meteor.user(), ["admin"])) {
               console.log('role: admin');
               ssSideNav.setVisible('toogle_admin', true);
            }else{
               ssSideNav.setVisible('toogle_admin', false);
            }

          });

          vm.helpers({
            isLoggedIn: () => {
              return Meteor.userId() !== null;
            },
            currentUser: () => {
              return Meteor.user();
            }
          });

          vm.logout = () => {
            Accounts.logout();
            $state.go('welcome');
          }
          function toggleSidenav (id) {
            if(Meteor.userId() !== null){
              //只有登录后才能打开左边菜单栏
              $mdSidenav(id).toggle()
            }
          }

      }

})();`

**Comment by sathishc** [comment]
I received the same error. It appears when I do this.

`$reactive(this).attach($rootScope);` in my main angular app.run method.

**Comment by ikostic** [comment]
+1

**Comment by insidemybrain** [comment]
+1

**Comment by fpaboim** [comment]
+1 same here with the viewmodel problem

**Comment by Urigo** [comment]
why would you want to use reactivity on the $rootScope?
I believe it's a bad practice but please show me use cases and let's see if it's something we really want to support

**Comment by Urigo** [comment]
why would you want to use reactivity on the $rootScope?
I believe it's a bad practice but please show me use cases and let's see if it's something we really want to support

**Comment by cleor41** [comment]
It was supported until not too long ago. Not saying it should be supported but it was an awkward error to get out of the blue. As an example though, lets say I have a notifications collection. This is a collection in it's own right and not a subfield of the user object. No matter where a user goes in the application, the user needs to be notified when they get a message. Without the ability to put it on the $rootScope, I would have to make a trivial component that sits directly under the $rootScope and use that instead.

Is there a downside to having reactivity on the rootScope? Is it less performant?

**Comment by DAB0mB** [comment]
@cleor41 The thing is that once you define variables on the $rootScope there will be a computation and a watcher running behind the scene, and since the $rootScope doesn't have any destruction mechanism there might be a potential memory leak. `angular-meteor` doesn't let you define any variables on the $rootScope to make sure you don't face these problems. Do you think it's a necessary thing? Or do you have any suggestions?

**Comment by cleor41** [comment]
@DAB0mB I see, as long as you understand the risks and don't abuse it in your application I don't think it's that bad. Global state is frowned upon across the board but in some applications, a collection should never be deconstructed. Putting these collections on the $rootScope just seems like the cleanest way to accomplish this.

**Comment by cleor41** [comment]
Maybe there's a way to factor this code out and include it if necessary? I'd be happy to help out wherever

**Comment by cleor41** [comment]
Unless it's painful to re-implement or it reduces performance for 80% of the other use cases out there, even if they don't make the $rootScope reactive, I don't see why this has to be enforced. Just seems like an unnecessary restriction. If this does stay as is, the docs should at least be changed to reflect this because it seems like a few people had this issue

**Comment by Urigo** [comment]
@cleor41 yes this is a good point.
Adding it back is not hard but I would love to hear more opinions about that before doing so as there are definitely better solutions to do that in your app.
On the other hand, it's your responsibility...

**Comment by cleor41** [comment]
@Urigo fair enough, it was a contrived example, I'm curious to hear others opinions also

**Comment by nunof07** [comment]
In my case I have a couple of directives used in the main template, for example a header with menus, etc. and I need the reactivity to know if the user is logged in or to access other data.

For example, I have something similar to this:

```
<body ng-app="myapp" ng-strict-di="">
    <my-header></my-header>
    <my-alerts></my-alerts>
    <main ui-view=""></main>
    <my-footer></my-footer>
</body>
```

And some of those directives need the reactivity. Should I be doing this differently?

**Comment by ozsay** [comment]
The performance impact of using `$rootScope` as a reactive context is individual to the use case. After each run of `autorun` (`helpers` is implemented with `autorun`) `angular-meteor` calls `$digest` on the scope. If you set a `helper `or a `autorun `on the `$rootScope`, after each run `angular` will check all of the watchers of the `$rootScope` and **all of it's children**. This can cause a big performance problem.

**Comment by cleor41** [comment]
@ozsay so in effect, that is no different then placing a directive right under the $rootScope and nesting all of your states from that directive. I think that's what most people do anyway. Does this also break any libraries out there?

As an alternative then, should we use the event listener paradigm more frequently? What are some of the things you guys do to solve problems like @nunof07's?

**Comment by DerekFong1004** [comment]
+1 Having the same problem after updating to 1.3.6.

**Comment by Urigo** [comment]
ok we will add it in 1.3.7.  hopefully today.

**Comment by insidemybrain** [comment]
@Urigo Thank you 😸😸😸

**Comment by cubitworx** [comment]
FYI, my answer above was simply to confirm for testing purposes. I personally don't need it & think it is bad design practice to put anything on $rootScope.

**Comment by Urigo** [comment]
Please try `1.3.7-beta.1_1` and let me know if it's working for your scenarios.
thanks

**Comment by insidemybrain** [comment]
@Urigo Everything is fine now! Thank you. But, should we open a poll on Meteor's forum? Because I've read too many comments about remove this support from Meteor.

**Comment by danimbrogno** [comment]
@Urigo Would it be possible to make 1.3.7-beta.1_1 available through npm?

**Comment by NoOneStopsMe** [comment]
Hey @Urigo ! Can it be possible if you also update official Atmosphere package to 1.3.7.beta.1 ? Thanks in advance and really appreciated :)

**Comment by kamilkisiela** [comment]
@danimbrogno As far I know `1.3.7-beta.1_1` on atmosphere is the same as `1.3.7-beta.1` on npm.

@NoOneStopsMe `meteor show --show-all angular` shows that there is a `1.3.7-beta.1` version available  on the atmosphere, `1.3.7-beta.1_1` too. I recommend to use second one.

**Comment by danimbrogno** [comment]
@kamilkisiela Ah I thought I was still getting the scope.viewModel error because I wasn't running the latest code. Turns out the issue was I had my module depend on 'angular-meteor.reactive' instead of the root module 'angular-meteor'. Problem solved.

**Comment by kamilkisiela** [comment]
@danimbrogno That's nice :+1:

**Comment by Urigo** [comment]
1.3.7 is out and this is fixed

**Comment by hanselke** [comment]
Sorry guys, ive re-read the thread twice and clicked all the links involved.

Not sure what the final decision is, are $rootScopes allowed to be $reactive or not?
