### ISSUE TITLE
Angular 5 migrating meteor 1.6 to 1.6.1.1: Cannot find module .html

### ISSUE THREAD

**Issue by onhate** [Urigo/angular-meteor#1916]
I have an application running on meteor 1.6 and after upgrading to 1.6.1.1 I get the following error on browser console:

`Uncaught Error: Cannot find module './app.template.html'`

Looks like I'm missing some dependency or configuration, could you please help me to check the sample project and tell me what is wrong?

I have created a replica of my project with all other dependencies I have in the project and only a single set of files to reproduce the issue.

**Angular Version**: 5.2.11
**Meteor Version**: 1.6.1.1

Steps to reproduce:
```
git clone https://github.com/onhate/meteor-1.6.1.1-upgrade-issue
cd meteor-1.6.1.1-upgrade-issue
npm install
npm start
```

**Comment by ardatan** [comment]
Thank you for your collaboration! However, this is not an issue because the way we import the template files has been changed;
https://github.com/Urigo/angular-meteor/blob/master/examples/MeteorCLI/bare/client/imports/app/app.component.ts

**Comment by ardatan** [comment]
We don’t support it anymore, so you can only use Angular’s way to import htmls like in the example
