### ISSUE TITLE
Accounts.user is not a function

### ISSUE THREAD

**Issue by kevinfiraguay** [Urigo/angular-meteor#1349]
Hi,
I use angular application for my client app outside meteor, and use meteor only server side, using angular-client-side to connect to meteor. I have an application with angular-meteor 1.3.2 and it works well that way. I tried to upgrade angular-meteor to version to 1.3.9, upgrade meteor to 1.3.1 and angular-client-side to 1.3.1. 

When I run the application, it throws "Accounts.user is not a function" before the applications start
coming from the line 92 in the angular-meteor-auth.js file 
`   vm.currentUser = Accounts.user();`
 if I check the object, indeed there is no function named user in the Accounts object.
is anyone knows what i'm doing wrong?
Thanks for your help

**Comment by kevinfiraguay** [comment]
If it helps, i tried to reproduce the problem with minimal packages. 

{
  "name": "test_bundle",
  "description": "",
  "license": "MIT",
  "dependencies": {
    "meteor-client-side": "=1.2.1",
    "accounts-password-client-side": "=0.3.1",
    "accounts-base-client-side": "=0.1.1",
    "angular-meteor": "=1.3.6",
    "angular-meteor-auth": "=0.2.2"
  }
}

Still the same error : 

`angular.js:12416 TypeError: Accounts.user is not a function`

but it works well with the same on 1.3.5. when the auth package is a part of angular-meteor. Does anyone make accounts-base-client-side working with angular-meteor-auth?

Thanks

**Comment by kevinfiraguay** [comment]
ok, after multiples test I found a solution: 
I needed to extract a new version accounts-base-client-side through the bash script that comes with the repo. 
But it did not worked at first. I had to add thoses dependencies to the concat phase to make it work
cat "$PACKAGES_PATH/modules-runtime.js" >> $OUTPUT_PATH/$NAME.bundle.js
cat "$PACKAGES_PATH/modules.js" >> $OUTPUT_PATH/$NAME.bundle.js
cat "$PACKAGES_PATH/babel-runtime.js" >> $OUTPUT_PATH/$NAME.bundle.js

I don't know if it's a good solution or if it's supposed to work without this (feel free to give me you thoughts about it), anyway you can close the ticket.

Thanks

**Comment by leizard** [comment]
I met the same issue. `bower install accounts-base-client-side` doesn't work for me.

**Comment by ferranalvarez** [comment]
Any progress on this? Have spent some time without success.. I can't fix the  "Accounts.user is not a function"

**Comment by kevinfiraguay** [comment]
Did you try the solution I suggested? The accounts-base-client-side is clearly missing dependencies since it has been built before meteor 1.3 / angular-meteor 1.3.6 and that's why it doesnt work.

**Comment by ntoka** [comment]
@kevinfiraguay your solution did not help me. Did I understand correctly that you modified accounts-base-client-side/bundle-min.sh script?

**Comment by idanwe** [comment]
I released new bundles for accounts-base-client-side#v1.2.8 and accounts-password-client-side#v1.1.11 that fixes the missing functionality.
And now the packages are matching the meteor's origin versions
